# Use the official Node.js 18 image from Microsoft
FROM mcr.microsoft.com/devcontainers/typescript-node:20

# Set the working directory inside the container
WORKDIR /workspace

# This command just keeps the container running.
CMD ["sleep", "infinity"]