version: '3.8'
services:
  # Our Node.js application service
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db

  # Our PostgreSQL database service
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vscode
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hr_db

volumes:
  postgres-data: